/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/studio/starlog-theme.ts
 * Command: astryx theme build src/studio/starlog-theme.ts
 * CLI: @astryxdesign/cli@0.6.3-canary.f04b501
 * Core: @astryxdesign/core@0.6.3-canary.f04b501
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
