/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/studio/starlog-theme.ts
 * Command: astryx theme build src/studio/starlog-theme.ts
 * CLI: @astryxdesign/cli@0.6.3-canary.f04b501
 * Core: @astryxdesign/core@0.6.3-canary.f04b501
 */

/// <reference path="./starlog.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const starlogTheme: DefinedTheme;
